name: create-customer-rancher-deployment
on:
  issues:
    branches:
      - master
      - main
    types: [opened]

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  validate:
    - uses: ./.github/workflows/validate-and-update-issue-with-result.yaml
      name: Configuring Longhorn and ArgoCD
      with:
        ISSUE_BODY: ${{github.event.issue.body}}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      
