name: Validate and Update Issue with Result
on:
  workflow_call:
    inputs:
      ISSUE_BODY:
        description: "Body of the issue associated with the PR"
        type: string
        required: true
      ISSUE_NUMBER:
        description: "Number of issue assocaited with the PR"
        type: string
        required: true

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: write

jobs:
  parse-issue-body:
    runs-on: ubuntu-latest
    steps:
    - uses: stefanbuck/github-issue-parser@v3
      name: Get Issue Body
      with:
        template-path: .github/ISSUE_TEMPLATE/create-rancher-deployment.yaml
        issue-body: ${{ inputs.ISSUE_BODY }}
  
  parse-and-validate-issue-body:
    name: Parse and validate the issue body
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.check-cluster-name.outputs.passed }}
    steps:
      - name: Validate the cluster name 
        id: check-cluster-name
        run: |
          if [[ ${{ steps.issue-parser.outputs.issueparser_cluster-name }} =~ [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ && 
            ${#steps.issue-parser.outputs.issueparser_cluster-name} -le 30 ]]; then
              echo "passed=true" >> $GITHUB_OUTPUT
          fi

  update-issue-with-job-result:
    name: Update Issue with Job Result
    runs-on: ubuntu-latest
    needs: parse-and-validate-issue-body
    outputs:
      passed: ${{ needs.parse-and-validate-issue-body.outputs.passed }}
    steps:
      - uses: actions/checkout@v3

      - name: Adding Success Comment
        if: ${{ needs.parse-and-validate-issue-body.outputs.passed }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ inputs.ISSUE_NUMBER }}
          body: |
            PASSED: Cluster name valid, proceeding to next step.
          reactions: +1,rocket

      - name: Adding Failed Comment
        if: ${{ !needs.parse-and-validate-issue-body.outputs.passed }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ inputs.ISSUE_NUMBER }}
          body: |
            FAILED: Cluster name should be in kebab-case, and must include upto 30 characters only. 
          reactions: -1,confused

